---
name: Tika-Gotenberg
version: dev
slug: tika-gotenberg
url: https://github.com/arwindersingh82/tika-gotenberg-home-assistant-addon
init: false
description: An extension for paperless addon to use Tika and Gotenberg
arch:
  - aarch64
  - amd64
startup: system
ports:
  3000/tcp: null
  9998/tcp: null
ports_description:
  3000/tcp: Gotenberg
  9998/tcp: Tika
